name: GitHub Actions Demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
    build:
        # ...
        runs-on: ubuntu-latest
        steps:

         - name: Check out 
           uses: actions/checkout@v2

         - name: Get short SHA
           run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

         - name: Build
           uses: docker/build-push-action@v2
           with:
             tags: romaintestu/my-tweet-app-lacework:${{ env.GHA_SHA }},romaintestu/my-tweet-app-lacework:latest
             load: true

         - name: lw-scanner engie
           uses: lacework/lw-scanner-action@v0.6.0
           with:
             LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
             LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}   
             IMAGE_NAME: romaintestu/my-tweet-app-lacework
             IMAGE_TAG: ${{ env.GHA_SHA }}
             SAVE_RESULTS_IN_LACEWORK: true
             SAVE_BUILD_REPORT: true
             BUILD_REPORT_FILE_NAME: myreport.html
             FAIL_BUILD: true
             SEVERITY_THRESHOLD: fixable
             LW_SCANNER_DISABLE_LIBRARY_PACKAGES_SCANNING: true
             USE_POLICY: true
            
         - name: Context
           if: ${{ failure() }} 
           run: echo Context ${{ toJSON(steps.lw-scanner.outputs) }}
           
#         - name: Login Jira test 2
#           if: ${{ failure() }}   
#           uses: atlassian/gajira-login@master
#           env:
#            JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
  #       - name: Create
  #         if: ${{failure()}}  
  #         id: create
  #         uses: atlassian/gajira-create@master
  #         with:
  #            project: SP
  #            issuetype: Task
  #            summary: |
  #              Docker Image Build : romaintestu/my-tweet-app-lacework
  #            description: |
  #              Des vulnérabilités critiques ont été détectées par Lacework lors du Build sur l'image romaintestu/my-tweet-app-lacework. Cette image doit être patchée avant déploiement.
  #              Veuillez consulter le rapport dans Lacework : https://lwintadriandaniels.fra.lacework.net/ui/investigation/container/ContainerVulnerabilityDashboardUx3?accountName=lwintromaintestu&filters=eyJWdWxuX0ZpbHRlcnMuTlVNX0ZJWEVTIjpbeyJ0aXRsZSI6MSwidmFsdWUiOjF9XSwic2VhcmNoIjoicm9tYWludGVzdHUvbXktdHdlZXQtYXBwLWxhY2V3b3JrIn0%3D&parameters=eyJncm91cEJ5IjoiZGVmYXVsdCIsInN0YXJ0VGltZSI6MTYzOTI5OTYwMDAwMCwiZW5kVGltZSI6MTYzOTU2MjQwMDAwMCwicHJlc2V0IjoiUGFzdCAzIGRheXMifQ%3D%3D&ci=LWINTROM_DE361628BC150784965C98EE89D80B3C068537EF7030931
  #              
  #            fields: ''
  #         
  #       - name: Log
  #         run: 
  #            echo "Scanner executed ${{ steps.lw-scanner.outputs.* }}"
  #            echo "Scanner executed NAME ${{ steps.lw-scanner.outputs.name }}"          

         - name: Login to DockerHub
           uses: docker/login-action@v1
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: tag and push
           uses: docker/build-push-action@v2
           with:
             push: true
             tags: romaintestu/my-tweet-app-lacework:${{ env.GHA_SHA }},romaintestu/my-tweet-app-lacework:latest,romaintestu/my-tweet-app-lacework:production
